highlight discussion time minimum
radicle-foundation/radworks-governance pull request #44
Opened 2023-09-06 12:28 UTC by shelbeeee

2023-09-07 08:29 UTC, abbey-titcomb requested changes
fixed some grammar

2023-09-07 08:29 UTC, abbey-titcomb commented on manual.md
> +> **Proposals can be posted to the forum for Discussion at anytime throughout the monthly cycle, but requires at least 7 days on the forum to be considered for that month’s voting cycle. If proposal
```suggestion
> **Proposals can be posted to the forum for Discussion at any time throughout the monthly cycle but require at least 7 days on the forum to be considered for that month's voting cycle. If proposals are posted after the second Monday deadline of a proposal cycle, they will be included in the next cycle. New proposals should be posted in the [Proposal Discussions](https://community.radworks.org/c/governance/discussions/19) sub-category under the Governance category on the forum.**
```

2023-09-08 09:11 UTC, shelbeeee reviewed
lgtm

2023-09-08 14:17 UTC, abbey-titcomb approved these changes
looks great!

2023-09-08 14:17 UTC, merged